config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  #ホームページ
  root 'static_pages#home' 
  
  #ログインフォーム
  get "/login", to:"sessions#new" 
  post "/login", to:"sessions#create"
  delete "/logout", to:"sessions#destroy"  
  resources :users
  resources :account_activations, only:[:edit] #edit_account_activation_url(token) URL:/account_activation/token/edit
  resources :posts, only:[:create,:new,:edit,:show,:update,:destroy]

  get "/search" ,to:"posts#search"
end

app/views/layouts/_sidebar.html.erb
<div class="sidebar">
  <div>
    <% @categories.each do |category| %>
      <div class="sidebar_category"><%= link_to "#{category.name}", search_path(search_category: category.name) %></div>
    <% end %>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FaqApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  </head>

  <body>
    <div class="header">
     <div class="header_left header_item"><%= link_to("FAQ_APP",root_path)%></div>
     <div class="header_middle">
      <%= form_with(url: search_path, method: :get, local: true) do |f|%>
        <%= f.hidden_field :search_category,value: @search_category %>
        <%= f.text_field :search_content, class:"search_form",placeholder:"\uf002  キーワード検索",value: @value%>
      <% end %>
     </div>
     <div class="header_right">
      <% if logged_in? %>
      <li class="header_item"><%= link_to("新規投稿",new_post_path)%></li>
      <li class="header_item"><%= link_to("ユーザー一覧",users_path)%></li>
      <li class="dropdown header_item">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="header_dropdown_menu"><%= @current_user.name%></a>
        <ul class="dropdown-menu dropdown-menu-right">
          <%# user_path(@current_user.id) %>
          <li class="header_dropdown_menu_list"><%= link_to "プロフィール",current_user %></li>
          <li class="header_dropdown_menu_list"><%= link_to "設定",edit_user_path(current_user) %></li>
          <li class="dropdown-divider"></li>
          <li class="header_dropdown_menu_list"><%= link_to "ログアウト",logout_path, method: :delete %></li>
        </ul>
      </li>
      <% else %>
        <li class="header_item"><%= link_to("ログイン",login_path)%></li>
        <li class="header_item"><%= link_to("新規登録",new_user_path)%></li>
      <% end %>
     </div>
    </div>
    <% flash.each do |message_type,message| %>
      <div class="alert alert-<%=message_type%>"> <%= message %> </div>
    <% end %>
    <%= yield %>
    <%# 開発環境のみ表示 Rails.envは環境の論理値を取る %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>